# Get all features for all filter settings
imageType:
    Original: {}
    Wavelet: {}
    LoG: 
      sigma: [2.0, 3.0, 4.0, 5.0]
    Square: {}
    SquareRoot: {}
    Logarithm: {}
    Exponential: {}
    Gradient: {}
    LBP2D: {}
    LBP3D: {}

featureClass:
    shape: 
    firstorder:
    glcm: 
    glrlm: 
    glszm: 
    gldm:
    ngtdm: 

setting:
    binWidth: 25
    interpolator: 'sitkBSpline'
    resampledPixelSpacing: [1, 1, 1]
    padDistance: 10
    voxelArrayShift: 1000

