meta:
  name: radiomic_snakemake_RADCURE
  experiment: snakemake_RADCURE

file_paths:
  top_dir: "/home/bioinf/bhklab/jermiah/RadioGenomics/pipelines/RADCURE_radiomics/orcestradata/radiomics/radcure_test_sample/"
  image_dir: "/home/bioinf/bhklab/jermiah/RadioGenomics/pipelines/RADCURE_radiomics/orcestradata/radiomics/radcure_test_sample/images"
  segmentation_dir: "/home/bioinf/bhklab/jermiah/RadioGenomics/pipelines/RADCURE_radiomics/orcestradata/radiomics/radcure_test_sample/"
  clinical_feature_file: "RADCURE_TCIA_Clinical June 13 2023.xlsx"
  output_dir: "data/radiomic_output/"

clinical_data:
  outcome_status:
  id_column_label: "Case_ID"
  na_value: "Unknown"

radiomic_extraction:
  segmentation_modality: 'RTSTRUCT'
  id_column_label: 'patient_ID'
  segmentation_label: 1
  roi_names: 'GTVp.*'
  pyrad_param_file: "scripts/radiomic_extraction/pyradiomics/pyrad_settings/settings_original_allFeatures.yaml"
  negative_control: True
  parallel: True

quality_checks: False